### PR TITLE
minor change to colourbar

### PR DESCRIPTION
**Pull request by jdtournier**
Screenshot (29)

### CODE REVIEW

**Comment by dchristiaens** [comment]
This didn't display on iTerm2 without b60d636. 

Probably best to first merge #23 as it fixes the colour bar scaling.

**Comment by jdtournier** [comment]
> Probably best to first merge #23 as it fixes the colour bar scaling.

:+1:

**Comment by maxpietsch** [comment]
5f8b152 as I think it makes sense to highlight what is changed, which is not the voxel value.

**Comment by jdtournier** [comment]
Unfortunately, I think that additional endline is messing things up on my end...

Screenshot from 2020-06-21 08-34-33

**Comment by dchristiaens** [comment]
How about a one-line layout as suggested in 0cd501c? Best would be if the colour scale could be aligned to the right of the image, but that seems like a pain to implement..

Screenshot 2020-06-21 at 10 58 12

**Comment by dchristiaens** [comment]
On that note, I was wondering if it wouldn't be easier to embed the colour scale in the bottom right  corner of the main image?

**Comment by jdtournier** [comment]
I think it would be, yes. But that depends on the backend you've set up for the orthoview, which I've yet to check out... I'll look at it
ASAP.

**Comment by maxpietsch** [comment]
I'd also integrate the colour bar into the main image, rendering multiple sixels seems to cost some performance on my system. Also makes sense as the colour bar only needs to be visible when the image is shown (the plot tool doesn't need it) and we can't update only the colour bar as the image needs to be adjusted as well.

**Comment by dchristiaens** [comment]
> But that depends on the backend you've set up for the orthoview, which I've yet to check out...

The changes in `sixel.h` are minimal: I've simply extended `Encoder` to `Encoder<H,V>` where H and V are the number of horizontal and vertical grid panels. A `set_panel(k)` method selects the active panel. As such, this could also be used for a Lightbox mode or for a side-by-side comparison of two images.

Plotting the colour bar could thus be done in the same way as plotting the crosshairs. In orthoview mode, you'd only need to trigger its display once (in the right-most panel). I think it would be good to have the option to draw colour bars in every panel, for instance for such side-by-side comparisons.

**Comment by dchristiaens** [comment]
How is this?
Screenshot 2020-06-21 at 23 36 17

Merging this with the orthoview branch will require a bit of intervention, but all quite easy. Which one is to be merged first?

**Comment by jdtournier** [comment]
Nice! Not sure it matters which you merge first - up to you.

Out of interest, how did you manage to line up the intensity range with the right of the image? Or was that just a 'lucky' shot...?

On a completely different note: I'm not sure I get what's going on with the colourbar. I notice it changes as the brightness/contrast is adjusted, so I'm assuming what we're seeing are the colours that would have been shown with the original (automatically determined) intensity mapping for the current min/max (?). Is that a good idea? It doesn't match what's shown in `mrview`, or the range of colours actually used in the display at that time. It's also relative to a potentially arbitrary and broadly unknown original scaling range (at least, the user won't necessarily have much of a clue what it was, and probably won't care either), and that scaling could have been completely off to begin with if the automatic scaling didn't work for some reason (e.g. lots of extreme nonsense values). The strategy used in `mrview` is to just show the full range of the _static_ colourmap and only update the intensities that the min & max actually correspond to, which I think is the most useful in practice (e.g. roughly what intensity does green correspond to when I display using the jet colourmap?). Thoughts?

**Comment by maxpietsch** [comment]
> Out of interest, how did you manage to line up the intensity range with the right of the image? Or was that just a 'lucky' shot...?

It's not automatic, I think it offended someone's senses :P 

> I'm not sure I get what's going on with the colourbar. I notice it changes as the brightness/contrast is adjusted

Yes, that was deliberate, what you were seeing were the range of colours currently displayed as in normal plots with colour bar. However, the colour bar values corresponding to the upper and lower ends are wrong.

image

With Daan's changes this is no longer the case and matches `mrview`'s behaviour of showing a static colourbar:
image

I am happy with either (if fixed) but for consistency sake I'd probably stick with the most recent `mrview`-like behaviour.

**Review by maxpietsch — APPROVED** [review]

**Comment by jdtournier** [comment]
:+1:

**Pull request merged**
