### PR TITLE
mrpeek: x switches arrow keys to interactive focus

### PR DESCRIPTION
**Pull request by maxpietsch**
x toggles arrow keys between inplane coordinates and slice/volumes

in 9eaf851, I tried to show the state:
- the active plane dimensions are highlighted by reversing the colour
- dimensions modified with arrow keys are underscored

image

but I guess d183578e6909bbdd73c022286a4515ee62121f82 is a better solution?
- the active plane dimensions are highlighted by underscore
- dimensions modified with arrow keys written in yellow (no background)

image image

### CODE REVIEW

**Comment by jdtournier** [comment]
I like the highlighting of the indices idea. Prefer different colour to background or underline though. 

On a different note: I'm not a huge fan of switching modes like this in this context (and yes, the irony of me using a modal editor like `vim` is not lost on me). I reckon we could map keys like:

- `i` :arrow_up:
- `k` :arrow_down:
- `j` :arrow_left:
- `l` :arrow_right:

I think that works on most keyboard layouts...?

**Comment by jdtournier** [comment]
I was also thinking we could add higher dimensional scrolling with the `[` & `]` keys, or `<` & `>`. Or probably better: have a key that changes the active dimension acted upon by :arrow_up: & :arrow_down: / scroll up/down. Maybe the `tab` key? We could then highlight the active dimension using a different colour from the ones affected by the cursor keys / left mouse drag?

**Comment by dchristiaens** [comment]
I like the idea of having a key to toggle between which dimensions are controlled by the up/down/left/right arrow keys. Using `x` feels intuitive to switch between crosshairs and slices/volumes.

Generally, I would favour keeping the controls as similar as possible to those in `mrview`. Muscle memory is a strong force... For this reason, I don't like `i/k/j/l` controls for the cursor since I expect `i` to toggle interpolation if available (I agree it's not a priority, but it's good te reserve the key). The `x` key is, afaik, not yet in use in `mrview`.

Similarly, I'd like to have Shift-Left and Shift-Right for the 5th dimension. Other controls of selecting what axes the arrow keys map to (Tab for instance) are an option, but may be confusing in sagittal or coronal views?

**Comment by jdtournier** [comment]
All good points. I was trying to avoid the shift left/right key combos since it's not uncommon for them to be mapped to different terminal actions (changing between tabs, for example, as is the case on my `tmux` setup). But I agree that by default, I think this one is available on most terminals. 

The `tab` key idea was only proposed to modify the dimension that the up/down arrows control, and only really makes sense if the shift left/right control wasn't going to be used. 

How about this: have a key to toggle between two modes of action for the arrow keys (`x` in original proposal - could be the spacebar too if it's going to be used a lot):
1. up/down control slice, left/right control volume
2. all arrows control in-slice cursor location

Independently, offer the `tab` key to control which dimension (3+, volume and above) the left/right arrow keys will control when in mode 1. I would still try to avoid using the shift left/right keys here (even though I completely agree it would be nice to match `mrview` key bindings as much as possible), because there's no other way to access higher dimensions (in `mrview`, these can be accessed via the View tool). But I appreciate this is a very rare use case...

**Comment by jdtournier** [comment]
This also naturally extends to anything else that would otherwise requires mouse control. We could for instance use the arrow keys to control brightness/contrast, either: 

- use a toggle key - in which case we could offer a clear indication that we're in brightness/contrast control mode by altering the status line to show the min/max values of the range, possibly in a different colour again;

- or use any modifier not captured by the terminal. I'm thinking we can bind all possible combination of modifiers for a given key to the same action, so that e.g. Shift-left, Alt-left, Ctrl-left, Win-left all perform the same action - in the hope that on any given system, at least one of these is not captured by the terminal or window manager...

**Comment by maxpietsch** [comment]
- b: colour bar and extreme values
- x: cycles through arrow key modes, mode is shown via yellow font

this cycle can be extended to slice + volume group, ... but then it starts to feel a bit complicated

default: slice / volume mode
image

focus mode:
image

colour mode:
image

**Comment by dchristiaens** [comment]
> * x: cycles through arrow key modes, mode is shown via yellow font

I would prefer a separate toggle key for brightness control, and have `x` _only_ toggle the focus position. I was wondering if we could use `b` for that? This would mean that the colour bar is only visible when changing the intensity, but that is good enough for my needs.



> How about this: have a key to toggle between two modes of action for the arrow keys (`x` in original proposal - could be the spacebar too if it's going to be used a lot):
> 
> 1. up/down control slice, left/right control volume
> 2. all arrows control in-slice cursor location
> 
> Independently, offer the `tab` key to control which dimension (3+, volume and above) the left/right arrow keys will control when in mode 1.

I like the sound of this. The text highlighting would then need to be updated too, to indicate which dimension is selected with the `tab` key.

**Comment by jdtournier** [comment]
I like it! I would use the spacebar to toggle personally - it's a high use thing, we need to minimise the mnemonic load on that one. 

I also agree with Daan regarding the separate toggle for the colourbar. But I think we can just show it all the time, it's not intrusive. It would be better to have it at the end of the colourbar as you show in your screenshots - it's on a separate line on my system.

**Comment by jdtournier** [comment]
By the way, I reckon we can merge this. We can refine later, but it's definitely an improvement, and there's no bugs that I can see.

**Review by jdtournier — APPROVED** [review]

**Comment by dchristiaens** [comment]
> I also agree with Daan regarding the separate toggle for the colourbar. But I think we can just show it all the time, it's not intrusive.
> By the way, I reckon we can merge this. We can refine later, but it's definitely an improvement, and there's no bugs that I can see.

Maybe make a small change to always show the colour scale and toggle brightness control with `b` before we merge? Then refine the layout later?

**Comment by jdtournier** [comment]
Yep, happy with that.

**Comment by dchristiaens** [comment]
OK, I'm changing it now.

**Comment by dchristiaens** [comment]
@maxpietsch are you happy with keeping brightness control separate?

**Pull request merged**
