### PR TITLE
Query functionality and other fixes

### PR DESCRIPTION
**Pull request by jdtournier**
This adds a function to request user input from the user. This is used here to set the number of colourmap levels, but may very well come in handy for other things as features are added in due course. 

Also fixes a few things with brightness/contrast handling and the handling of mouse move events.

### CODE REVIEW

**Comment by jdtournier** [comment]
On that note, it's quite interesting to have a look at the effect of the number of colourmap levels on visual quality. I reckon we could drop to 32 levels without a massive hit in quality, and (roughly) half the frame size. Dropping to 16 is clearly not so great, and 8 is plain bad. Dropping to 1 allows the user to visually threshold the image - who knows, might come in handy...

**Comment by maxpietsch** [comment]
right+drag contrast seems to be broken in iTerm2 and mlterm, I get either a black, the initial, or a white image. Seems to depends on the image intensity range, T1 is fine, fod is not.

**Comment by jdtournier** [comment]
Bummer... Can you pinpoint which is the offending commit...?

**Comment by jdtournier** [comment]
This branch seems to work fine when used over the network on a Windows system with minTTY. Not sure what the problem is on your end exactly... Maybe it's data specific?

**Comment by maxpietsch** [comment]
Yes, the problem is that the _relative_ offset change rate is intensity range dependent. 8b2e24d795af04365ed6326665bc77cf547b096e changes the behaviour but is not the real reason. Divide the image by its max value or multiply by 1000 and change the offset for each with right-click x drag to reproduce.

**Comment by maxpietsch** [comment]
image

after one x drag:
image

**Comment by jdtournier** [comment]
Darn. That's precisely what I was trying to avoid...

**Comment by jdtournier** [comment]
OK, I reckon that's fixed the colourmap update. Seems to behave the same with very different scales or different number of colourmap levels. Should be good to go this time... :crossed_fingers:

**Review by maxpietsch — APPROVED** [review]
fixed the scale issue on iTerm2 and mlterm

**Pull request merged**
